rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
branches:
  only:
    - master
notifications:
  email:
    - michal@casanowak.com 
env:
  - PUPPET_VERSION=2.7.11
  - PUPPET_VERSION=2.7.14
  - PUPPET_VERSION=2.7.17
  - PUPPET_VERSION=2.7.18
